/**
 * Preview/demo bootstrap (957a6bce, also used by 553eea82's preview).
 *
 * When `VITE_DEMO=true` at build time, populates the board store with
 * representative seed data so launch_preview containers can show realistic
 * UI without booting the orchestrator + postgres stack.
 *
 * Imported and called once from main.tsx, before React mounts.
 */
import type {
  ActivityItem,
  Agent,
  AgentMessage,
  Approval,
  Commit,
  Preview,
  Sprint,
  Task,
} from './types';
import { useBoardStore } from './store';

const now = Date.now();
const at = (secondsAgo: number): string => new Date(now - secondsAgo * 1000).toISOString();

const A: Agent[] = [
  {
    id: 'agent-lucas-frontend',
    name: 'lucas-frontend',
    role: 'frontend',
    personaPath: 'agents/frontend.md',
    sessionId: null,
    status: 'working',
    worktreePath: null,
    createdAt: at(86_400),
  },
  {
    id: 'agent-bruno-backend',
    name: 'bruno-backend',
    role: 'backend',
    personaPath: 'agents/backend.md',
    sessionId: null,
    status: 'idle',
    worktreePath: null,
    createdAt: at(86_400),
  },
  {
    id: 'agent-uma-uiux',
    name: 'uma-uiux',
    role: 'ui-ux',
    personaPath: 'agents/ui-ux.md',
    sessionId: null,
    status: 'idle',
    worktreePath: null,
    createdAt: at(86_400),
  },
  {
    id: 'agent-quin-qa',
    name: 'quin-qa',
    role: 'qa',
    personaPath: 'agents/qa.md',
    sessionId: null,
    status: 'idle',
    worktreePath: null,
    createdAt: at(86_400),
  },
  {
    id: 'agent-sage-cybersec',
    name: 'sage-cybersec',
    role: 'cybersec',
    personaPath: 'agents/cybersec.md',
    sessionId: null,
    status: 'working',
    worktreePath: null,
    createdAt: at(86_400),
  },
  {
    id: 'agent-leo-langs',
    name: 'leo-langs',
    role: 'lang-specialist',
    personaPath: 'agents/lang-specialist.md',
    sessionId: null,
    status: 'idle',
    worktreePath: null,
    createdAt: at(86_400),
  },
  {
    id: 'agent-alice-pm',
    name: 'alice-pm',
    role: 'pm',
    personaPath: 'agents/pm.md',
    sessionId: null,
    status: 'idle',
    worktreePath: null,
    createdAt: at(86_400),
  },
  {
    id: 'agent-dani-dba',
    name: 'dani-dba',
    role: 'dba',
    personaPath: 'agents/dba.md',
    sessionId: null,
    status: 'idle',
    worktreePath: null,
    createdAt: at(86_400),
  },
] as Agent[];

// Set of tasks chosen to land at least one card in every column so the
// kanban renders with content in every state. Mix of priorities (P1–P5)
// to validate the new two-tone pill rendering.
const T: Task[] = [
  {
    id: '553eea82-95a6-4229-a73a-8384e374e1d0',
    sprintId: null,
    title: 'Live activity feed on dashboard',
    description: 'Make agent activity visible at a glance on /dashboard.',
    status: 'review',
    assigneeId: 'agent-lucas-frontend',
    createdBy: null,
    priority: 2,
    parentId: null,
    branch: 'agent/lucas-frontend/task-553eea82',
    prUrl: 'https://example.com/pr/9',
    prNumber: 9,
    createdAt: at(7_200),
    updatedAt: at(900),
  },
  {
    id: '957a6bce-ea08-4ff1-a9e3-5b98b7e0c49b',
    sprintId: null,
    title: 'Polish wave: kanban task card (5 sub-items)',
    description: "uma-uiux's polish-wave: typography, 8pt rhythm, two-tone pills, hover/focus, skeleton + empty.",
    status: 'in_progress',
    assigneeId: 'agent-lucas-frontend',
    createdBy: null,
    priority: 3,
    parentId: null,
    branch: 'agent/lucas-frontend/task-957a6bce',
    createdAt: at(3_600),
    updatedAt: at(120),
  },
  {
    id: '54a15775-0f73-48ef-a2a8-5cc73e964684',
    sprintId: null,
    title: 'Polish: keyboard nav on the file tree',
    description: 'Roving tabindex on FileBrowser. Arrow up/down + Enter + Cmd+P preserved.',
    status: 'todo',
    assigneeId: 'agent-lucas-frontend',
    createdBy: null,
    priority: 4,
    parentId: null,
    createdAt: at(2_400),
    updatedAt: at(2_400),
  },
  {
    id: '46f8735d-d7a5-4d83-b7c4-3f2b15e8e2ea',
    sprintId: null,
    title: 'Security review: auth + setup flow',
    description: 'sage-cybersec running the audit; PR review on /api/setup/status.',
    status: 'in_progress',
    assigneeId: 'agent-sage-cybersec',
    createdBy: null,
    priority: 1,
    parentId: null,
    createdAt: at(7_200),
    updatedAt: at(300),
  },
  {
    id: '6a6152e7-1234-5678-9abc-def012345678',
    sprintId: null,
    title: 'Empty-state audit + house-style locks',
    description: 'leo-langs + uma-uiux: per-component empty-state strings.',
    status: 'review',
    assigneeId: 'agent-leo-langs',
    createdBy: null,
    priority: 3,
    parentId: null,
    branch: 'agent/leo-langs/task-edc7ef5c',
    prUrl: 'https://example.com/pr/7',
    prNumber: 7,
    createdAt: at(7_200),
    updatedAt: at(600),
  },
  {
    id: 'b49fc355-9876-5432-10fe-dcba98765432',
    sprintId: null,
    title: 'DB perf: spendSummary() full table scan',
    description: 'dani-dba: index activity_log(created_at desc).',
    status: 'backlog',
    assigneeId: 'agent-dani-dba',
    createdBy: null,
    priority: 2,
    parentId: null,
    createdAt: at(10_800),
    updatedAt: at(10_800),
  },
  {
    id: 'e6b4af02-1111-2222-3333-444455556666',
    sprintId: null,
    title: 'DB perf: hot-path indexes (assignee, approvals, previews, commits)',
    description: null,
    status: 'backlog',
    assigneeId: 'agent-dani-dba',
    createdBy: null,
    priority: 3,
    parentId: null,
    createdAt: at(10_800),
    updatedAt: at(10_800),
  },
  {
    id: '82448803-aaaa-bbbb-cccc-ddddeeeeffff',
    sprintId: null,
    title: 'Hero/footer breakpoint migration @1024 → @734',
    description: 'Apple-style landing page nav + hero rhythm.',
    status: 'done',
    assigneeId: 'agent-lucas-frontend',
    createdBy: null,
    priority: 4,
    parentId: null,
    branch: 'agent/lucas-frontend',
    prUrl: 'https://example.com/pr/3',
    prNumber: 3,
    createdAt: at(86_400 * 2),
    updatedAt: at(86_400),
  },
  {
    id: 'acd5e7a4-5555-6666-7777-888899990000',
    sprintId: null,
    title: 'Voice unification copy pass — 12 pages',
    description: null,
    status: 'todo',
    assigneeId: 'agent-leo-langs',
    createdBy: null,
    priority: 5,
    parentId: null,
    createdAt: at(7_200),
    updatedAt: at(7_200),
  },
] as unknown as Task[];

const ACT: ActivityItem[] = [
  {
    id: 30,
    agentId: 'agent-lucas-frontend',
    eventType: 'commit.created',
    payload: {
      sha: '8a4f1c0',
      message: 'feat(taskcard): polish-wave (typography, 8pt, two-tone pills, hover, skeleton)',
    },
    createdAt: at(20),
  },
  {
    id: 29,
    agentId: 'agent-leo-langs',
    eventType: 'message.sent',
    payload: {
      subject: 'Kanban column copy — use audit §4.3',
      messageType: 'answer',
      toAgentId: 'agent-lucas-frontend',
    },
    createdAt: at(180),
  },
  {
    id: 28,
    agentId: 'agent-lucas-frontend',
    eventType: 'task.updated',
    payload: { status: 'in_progress' },
    createdAt: at(420),
  },
  {
    id: 27,
    agentId: 'agent-sage-cybersec',
    eventType: 'agent.status',
    payload: { status: 'working' },
    createdAt: at(900),
  },
];

/** Apply seed to the store. Safe to call repeatedly (idempotent). */
export function bootstrapDemo(): void {
  useBoardStore.setState({
    agents: A,
    tasks: T,
    messages: [] as AgentMessage[],
    activity: ACT,
    commits: [] as Commit[],
    previews: [] as Preview[],
    approvals: [] as Approval[],
    sprints: [] as Sprint[],
    loaded: true,
    connectionError: null,
    wsStatus: 'open',
  });
}
